site_name: Dev beginner tutorial
site_description: Dev beginner tutorial
site_author: Sotetsu KOYAMADA
site_url: http://sotets.uk/dev-beginner-tutorial
repo_name: sotetsuk/dev-beginner-tutorial
repo_url: https://github.com/sotetsuk/dev-beginner-tutorial
copyright: Copyright &copy 2020 Sotetsu KOYAMADA
nav:
    - Home: index.md
    - 1. UNIXコマンド入門: unix_command.md
    - 2. Python入門: python.md
    - 3. Git入門: git.md
    - 4. GitHub入門: github.md
    - 5. Python総合演習: python_practice.md
    - 6. C++入門: cpp.md
    - 7. おわりに: conclusion.md
theme:
  name: material
  language: ja
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: teal
    accent: deep purple
  font:
    text: Noto Sans
    code: Inconsolata
markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
